name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
